# Generated by Django 3.2.9 on 2021-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(default=0, verbose_name='Question No.')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('correct_option', models.IntegerField(verbose_name='Answer')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('exam_name', models.CharField(max_length=255, verbose_name='Exam')),
                ('exam_year', models.IntegerField(verbose_name='Year')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
            ],
        ),
    ]
