# Generated by Django 3.2.9 on 2021-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='Question', max_length=255, verbose_name='Title'),
        ),
    ]
