# Generated by Django 3.2.9 on 2021-12-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211205_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
