# Generated by Django 3.2.9 on 2021-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_answers_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='technique',
            field=models.IntegerField(choices=[(0, 'Multiple Choice')], default=0, verbose_name='Type of Question'),
        ),
    ]
