# Generated by Django 3.2.9 on 2021-12-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_questions_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='title',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='q_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='technique',
        ),
    ]
