# Generated by Django 3.2.9 on 2021-12-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_questions_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='Question', max_length=255, verbose_name='Title'),
        ),
    ]
